bug/PDPDEVTOOL-1067
oracle/netsuite-suitecloud-sdk pull request #207
Opened 2020-08-28 12:04 UTC by lfpvillegas

2020-08-28 12:45 UTC, karl-anthony-ng requested changes

2020-08-28 12:45 UTC, karl-anthony-ng commented on packages/node-cli/src/commands/file/import/ImportFilesAction.js
> +			if(this._runInInteractiveMode == false) {
As Javi mentioned, please change to  "if (...".

2020-08-28 15:24 UTC, davidecorreu approved these changes

2020-08-31 10:58 UTC, vic-nik approved these changes

2020-08-31 10:59 UTC, merged