Fixed the Escape key not canceling the command
oracle/netsuite-suitecloud-sdk pull request #238
Opened 2020-10-13 14:17 UTC by x8a

- Fixed the problem of the escape key not canceling the command
- Edited the message
- Added the NetSuite domain constant

2020-10-14 08:19 UTC, karl-anthony-ng requested changes

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/messages.json
> +	"PRODUCTION_DOMAIN": "system.netsuite.com",
You can reuse the ApplicationConstants.PROD_ENVIRONMENT_ADDRESS from packages/nodecli. In vscode, ApplicationConstants is accessed via ExtensionUtil.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if (!authId || authId === undefined) {
!authId already checks for null, undefined, and empty string. So for this one, I think !authId should be enough.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +				if(!fieldValue) {
Please add a space after if. That's what we're using as standard for our code.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if(!authId || authId === undefined) {
I think !authId is enough here. No need to add authId === undefined.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if(!tokenId || tokenId === undefined) {
I think !tokenId should be enough here.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if(!tokenSecret || tokenSecret === undefined) {
I think !tokenSecret should be enough here.

2020-10-14 08:19 UTC, karl-anthony-ng commented on packages/vscode-extension/src/service/TranslationKeys.ts
> +export const PRODUCTION_DOMAIN = 'PRODUCTION_DOMAIN';
Please check my comment in ManageAccounts.ts.

2020-10-14 13:49 UTC, karl-anthony-ng requested changes

2020-10-14 13:49 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if (url === undefined) {
Can we use !url here?

2020-10-14 13:49 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +			if (!selected || selected === undefined) {
Can we use just !selected here?

2020-10-14 13:49 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if (url === undefined) {
Can we use !url here?

2020-10-14 13:52 UTC, x8a commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if (url === undefined) {
It didn't work.

2020-10-14 13:52 UTC, x8a commented on packages/vscode-extension/src/commands/ManageAccounts.ts
> +		if (url === undefined) {
It didn't work either.

2020-10-14 14:33 UTC, karl-anthony-ng approved these changes

2020-10-19 09:08 UTC, vic-nik approved these changes

2020-10-19 09:39 UTC, merged