feature/PDPDEVTOOL-3757-VSCode-account:setup-improve-output
oracle/netsuite-suitecloud-sdk pull request #240
Opened 2020-10-15 14:16 UTC by x8a

Logged the success message & display it in a pop-up window

2020-10-15 14:28 UTC, karl-anthony-ng commented on packages/vscode-extension/messages.json
> +	"MANAGE_ACCOUNTS_SELECT_AUTH_ID_SUCCESS": "The default account for the current project was successfully set to {0}.",
Good catch in noticing the missing period here.

2020-10-15 14:31 UTC, karl-anthony-ng requested changes

2020-10-15 14:31 UTC, karl-anthony-ng commented on packages/vscode-extension/src/commands/ManageAccounts.ts
>  			return;
Please remove the return in line 333, it's not necessary.

2020-10-15 15:10 UTC, karl-anthony-ng approved these changes

2020-10-19 09:07 UTC, vic-nik approved these changes

2020-10-19 09:39 UTC, merged