Feature/pdpdevtool 4541 vscode update instances
oracle/netsuite-suitecloud-sdk pull request #553
Opened 2022-03-11 09:21 UTC by antoniofruci

2022-03-11 10:58 UTC, lfpvillegas requested changes

2022-03-11 10:58 UTC, lfpvillegas commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +		if (includeInstancesAnswer === this.translationService.getMessage(ANSWERS.YES)) {
You could use previously defined constant.

2022-03-11 10:58 UTC, lfpvillegas commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +			if (!overwriteInstances || overwriteInstances === this.translationService.getMessage(ANSWERS.CANCEL)) {
you could use previously defined constant cancel (also in line 41)

2022-03-11 15:25 UTC, davidecorreu commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +		});
This should only be asked if the selected object is a custom record. There is some logic missing here.

2022-03-11 15:28 UTC, davidecorreu commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +			const overwriteInstances = await window.showQuickPick([continueMessage, cancelMessage], {
I'm not in favor of asking twice about overwriting, once for regular objects, and again for the instances of custom records. I think is a bad user experience for the developer. I would prefer to ask only once, either overwrite objects or overwrite objects and its instances.
I'm actually not sure that we could update more than one object at a time, but I would like to be only be asked about overwriting only once in any case.

2022-03-14 11:46 UTC, lfpvillegas commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +	private static isCustomRecord(scriptid: string): boolean {
we don't really need that this method is static, it is not called for anywhere else.

2022-03-14 12:08 UTC, davidecorreu commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +			}
I think we are missing the case were the user doesn't respond to the question or just hit ESC , in that case I think we should stop the command flow. Something like:
```
if (!includeInstancesAnswer) {
  return;
}
```

2022-03-14 12:11 UTC, davidecorreu commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +		const suiteCloudCommand = { scriptid: [scriptId], includeinstances: '' };
I would prefer to name this one `suiteCloudCommandOptions` / `commandOptions` or similar one with "options" in the name.

2022-03-14 14:46 UTC, antoniofruci commented on packages/vscode-extension/src/commands/UpdateObject.ts
> +			}
True, I'll move it

2022-03-15 12:19 UTC, lfpvillegas approved these changes

2022-03-15 12:19 UTC, merged