Merge for release
oracle/netsuite-suitecloud-sdk pull request #567
Opened 2022-04-12 15:09 UTC by antoniofruci

2022-04-12 15:34 UTC, karl-anthony-ng approved these changes

2022-04-12 16:06 UTC, tourajvaziri requested changes

2022-04-13 06:46 UTC, davidecorreu commented on packages/node-cli/README.md
> +|[`object:update`](https://system.netsuite.com/app/help/helpcenter.nl?fid=section_156050566547.html)|Overwrites the custom objects in the project with the custom objects from an account. In the case
I agree with Touraj.

2022-04-13 07:25 UTC, davidecorreu approved these changes

2022-04-13 07:41 UTC, merged