PDPDEVTOOL-4548: Change SDF project to SuiteCloud project
oracle/netsuite-suitecloud-sdk pull request #593
Opened 2022-07-18 07:25 UTC by karl-anthony-ng

2022-07-18 09:31 UTC, tourajvaziri requested changes
Hello, Also do we need to the same change for NSX?

2022-07-18 09:53 UTC, karl-anthony-ng commented on packages/unit-testing/README.md
> +**You successfully ran your first test for an SuiteCloud project!**
Updated.

2022-07-18 09:54 UTC, karl-anthony-ng commented
Only for NSN now. NSX will be updated in a later date.

2022-07-19 11:49 UTC, tourajvaziri approved these changes

2022-07-19 12:28 UTC, antoniofruci approved these changes

2022-07-19 12:28 UTC, merged